[[req_core_job-results-async-one]]
[requirement]
====
[%metadata]
identifier:: /req/core/job-results-async-one

[.component,class=conditions]
--
. The <<sc_execution_mode,negotiated execution mode>> is asynchronous,
. The number of requested (whether <<implicit-process-output,implicitly>> or <<explicit-process-output,explicitly>>) outputs in the <<execute-request-body,execute request>> is 1.
. The result is retrieved from the `/jobs/{jobID}/results/{outputID}` endpoint.
--

[.component,class=part]
--
The server SHALL respond with an HTTP status code of 200.
--

[.component,class=part]
--
In the response headers, the server SHALL include an HTTP header named `OGC-Output-Values-Count` indicating how many processing values are retrievable for this output.
--

[.component,class=part]
--
The media type of the response SHALL be as negotiated as per the https://datatracker.ietf.org/doc/html/rfc2616#section-12[HTTP content negotiation rules].
--

[.component,class=part]
--
The content of response body SHALL be the requested process output value in the negotiated output format.
--

====

NOTE: Unless the definition of an output sets `maxOccurs>1`, the value of the `OGC-Output-Values-Count` HTTP header will usually be 1.

NOTE: If the requested output is multi-valued (i.e. `maxOccurs>1` in the <<sc_process_description,process description>>), then the negotiated response will need to be some type of container for the array of values generated by the process for this output.  For example, this could be a JSON response where the array of values is encoded as a JSON array or a multi-part response where each part contains one value from the array or some archive (e.g. ZIP or tar) where each array value is stored in an individual file.

